# Generated by Django 5.2.16 on 2026-08-04 16:31

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exchanges', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название бота')),
                ('pair', models.CharField(help_text='В формате BASE/QUOTE, например BTC/USDT', max_length=30, verbose_name='Торговая пара')),
                ('direction', models.CharField(choices=[('long', 'Long'), ('short', 'Short')], max_length=10, verbose_name='Направление')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('running', 'Запущен'), ('paused', 'На паузе'), ('stopped', 'Остановлен'), ('error', 'Ошибка')], default='draft', max_length=10, verbose_name='Статус')),
                ('deposit', models.DecimalField(decimal_places=2, help_text='Сумма в валюте котировки (обычно USDT) на одну сделку', max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('1'))], verbose_name='Депозит')),
                ('reinvest', models.BooleanField(default=False, help_text='Прибавлять прибыль закрытых сделок к депозиту следующей', verbose_name='Реинвестировать')),
                ('leverage', models.PositiveSmallIntegerField(default=1, help_text='Только для фьючерсов. На споте всегда 1', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(125)], verbose_name='Плечо')),
                ('orders_count', models.PositiveSmallIntegerField(default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Количество ордеров сетки')),
                ('overlap_percent', models.DecimalField(decimal_places=4, default=Decimal('10'), help_text='На сколько % против позиции растянута сетка', max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='Перекрытие, %')),
                ('martingale_percent', models.DecimalField(decimal_places=4, default=Decimal('5'), help_text='На сколько % каждый следующий ордер крупнее предыдущего', max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1000'))], verbose_name='Мартингейл, %')),
                ('indent_percent', models.DecimalField(decimal_places=4, default=Decimal('0'), help_text='Отступ первого ордера от рыночной цены. 0 — вход по рынку', max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='Отступ, %')),
                ('logarithmic', models.BooleanField(default=False, help_text='Ордера гуще у цены входа, реже на удалении', verbose_name='Логарифмическое распределение')),
                ('log_ratio', models.DecimalField(decimal_places=2, default=Decimal('1.2'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('1')), django.core.validators.MaxValueValidator(Decimal('5'))], verbose_name='Коэффициент логарифма')),
                ('grid_pullup', models.BooleanField(default=False, help_text='Переставлять неисполненные ордера вслед за ценой', verbose_name='Подтяжка сетки')),
                ('take_profit_percent', models.DecimalField(decimal_places=4, default=Decimal('1'), help_text='От средней цены входа', max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='Тейк-профит, %')),
                ('stop_loss_enabled', models.BooleanField(default=False, verbose_name='Стоп-лосс')),
                ('stop_loss_percent', models.DecimalField(decimal_places=4, default=Decimal('20'), help_text='От средней цены входа', max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='Стоп-лосс, %')),
                ('stop_after_deal', models.BooleanField(default=False, help_text='Не начинать новый цикл после закрытия текущей сделки', verbose_name='Остановить после завершения сделки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exchange_account', models.ForeignKey(help_text='Тип рынка (спот/фьючерсы) определяется выбранным ключом', on_delete=django.db.models.deletion.PROTECT, related_name='bots', to='exchanges.exchangeaccount', verbose_name='API-ключ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bots', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Бот',
                'verbose_name_plural': 'Боты',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('waiting', 'Ожидает входа'), ('active', 'В позиции'), ('closing', 'Закрывается'), ('closed', 'Закрыта'), ('cancelled', 'Отменена'), ('failed', 'Ошибка')], default='waiting', max_length=10, verbose_name='Статус')),
                ('deposit', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Депозит сделки')),
                ('direction', models.CharField(choices=[('long', 'Long'), ('short', 'Short')], max_length=10)),
                ('pair', models.CharField(max_length=30)),
                ('entry_price', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='Цена первого входа')),
                ('average_price', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='Средняя цена')),
                ('exit_price', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='Цена выхода')),
                ('filled_base', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=24, verbose_name='Объём позиции')),
                ('filled_quote', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20, verbose_name='Вложено средств')),
                ('filled_orders', models.PositiveSmallIntegerField(default=0, verbose_name='Исполнено ордеров сетки')),
                ('profit', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Прибыль')),
                ('commission', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20, verbose_name='Комиссия биржи')),
                ('platform_fee', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20, verbose_name='Комиссия платформы')),
                ('error_message', models.TextField(blank=True, verbose_name='Текст ошибки')),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='bots.bot', verbose_name='Бот')),
            ],
            options={
                'verbose_name': 'Сделка',
                'verbose_name_plural': 'Сделки',
                'ordering': ('-opened_at',),
            },
        ),
        migrations.CreateModel(
            name='EntryFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.PositiveSmallIntegerField(default=1, help_text='Внутри группы условия объединяются через И, между группами — ИЛИ', verbose_name='Группа')),
                ('indicator', models.CharField(choices=[('rsi', 'RSI'), ('ema', 'EMA'), ('sma', 'SMA'), ('bb_lower', 'Bollinger Bands (нижняя)'), ('bb_upper', 'Bollinger Bands (верхняя)'), ('macd', 'MACD'), ('price', 'Цена')], max_length=20, verbose_name='Индикатор')),
                ('timeframe', models.CharField(default='15m', max_length=10, verbose_name='Таймфрейм')),
                ('period', models.PositiveSmallIntegerField(default=14, verbose_name='Период индикатора')),
                ('operator', models.CharField(choices=[('gt', 'Больше'), ('lt', 'Меньше'), ('cross_up', 'Пересекает вверх'), ('cross_down', 'Пересекает вниз')], max_length=15, verbose_name='Условие')),
                ('value', models.DecimalField(decimal_places=8, max_digits=20, verbose_name='Значение для сравнения')),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filters', to='bots.bot', verbose_name='Бот')),
            ],
            options={
                'verbose_name': 'Условие входа',
                'verbose_name_plural': 'Условия входа',
                'ordering': ('group', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('grid', 'Ордер сетки'), ('take_profit', 'Тейк-профит'), ('stop_loss', 'Стоп-лосс')], max_length=15, verbose_name='Тип')),
                ('status', models.CharField(choices=[('new', 'Создан'), ('placed', 'Выставлен'), ('partial', 'Частично исполнен'), ('filled', 'Исполнен'), ('cancelled', 'Отменён'), ('failed', 'Ошибка')], default='new', max_length=10, verbose_name='Статус')),
                ('grid_index', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Номер в сетке')),
                ('exchange_order_id', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='ID на бирже')),
                ('price', models.DecimalField(decimal_places=8, max_digits=20, verbose_name='Цена')),
                ('amount', models.DecimalField(decimal_places=8, max_digits=24, verbose_name='Объём в монете')),
                ('filled_amount', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=24, verbose_name='Исполнено')),
                ('quote_amount', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Сумма в котировке')),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='bots.deal', verbose_name='Сделка')),
            ],
            options={
                'verbose_name': 'Ордер',
                'verbose_name_plural': 'Ордера',
                'ordering': ('grid_index', 'id'),
            },
        ),
        migrations.AddIndex(
            model_name='bot',
            index=models.Index(fields=['status'], name='bot_status_idx'),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['bot', 'status'], name='deal_bot_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(fields=('deal', 'kind', 'grid_index'), name='unique_grid_order_per_deal'),
        ),
    ]
