# Generated by Django 5.2.16 on 2026-07-28 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0001_initial'),
        ('exchanges', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='direction',
            field=models.CharField(choices=[('long', 'Длинная позиция'), ('short', 'Короткая позиция')], default='long', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bot',
            name='exchanges_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exchanges', to='exchanges.exchangeaccount'),
        ),
    ]
