# Generated by Django 5.2.16 on 2026-08-04 16:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange', models.CharField(choices=[('okx', 'OKX'), ('bybit', 'Bybit'), ('binance', 'Binance')], default='okx', max_length=20, verbose_name='Биржа')),
                ('market_type', models.CharField(choices=[('spot', 'Спот'), ('futures', 'Фьючерсы')], default='spot', max_length=10, verbose_name='Тип рынка')),
                ('label', models.CharField(help_text='Чтобы отличать несколько ключей одной биржи', max_length=50, verbose_name='Название ключа')),
                ('api_key_encrypted', models.TextField(editable=False)),
                ('api_secret_encrypted', models.TextField(editable=False)),
                ('passphrase_encrypted', models.TextField(blank=True, editable=False)),
                ('is_testnet', models.BooleanField(default=True, help_text='Торговля на тестовой сети биржи, без реальных денег', verbose_name='Демо-режим')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('last_check_ok', models.BooleanField(blank=True, null=True, verbose_name='Последняя проверка связи')),
                ('last_check_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_accounts', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'API-ключ биржи',
                'verbose_name_plural': 'API-ключи бирж',
                'ordering': ('-created_at',),
                'constraints': [models.UniqueConstraint(fields=('user', 'label'), name='unique_label_per_user')],
            },
        ),
    ]
